In [8]:
import cv2
import mediapipe
import os
import numpy as np

In [9]:
drawingModule = mediapipe.solutions.drawing_utils
handsModule = mediapipe.solutions.hands

In [10]:
train_path = r'asl_dataset\asl_alphabet_train\asl_alphabet_train'
train_path = os.path.join(os.getcwd(), train_path)

In [11]:
def get_landmarks(frame):
    with handsModule.Hands(static_image_mode=False, min_detection_confidence=0.7, min_tracking_confidence=0.7, max_num_hands=2) as hands:
        results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        
        points = []
        if results.multi_hand_landmarks != None:
           for handLandmarks in results.multi_hand_landmarks:
               for point in handsModule.HandLandmark:
                   normalizedLandmark = handLandmarks.landmark[point]
                   pixelCoordinatesLandmark = drawingModule._normalized_to_pixel_coordinates(normalizedLandmark.x, normalizedLandmark.y, frameWidth, frameHeight)
                   #print(pixelCoordinatesLandmark)
                   cv2.circle(frame, pixelCoordinatesLandmark, 5, (0, 255, 0), -1)
                   points.append(pixelCoordinatesLandmark)
        
        if(len(points) == 21 or len(points) == 42):
            return [True, np.array(points)]
        else:
            return [False, np.array(points)];
        cv2.imshow('Test hand', frame)

In [18]:
categories = os.listdir(train_path)
#print(categories)
x = 0
for category in categories:
    path = os.path.join(train_path, category)
    for image_path in os.listdir(path):
        img = cv2.imread(os.path.join(path, image_path), cv2.IMREAD_GRAYSCALE)
        ret, landmarks = get_landmarks(img)
        #print(ret, landmarks)
        if(ret):
            x += 1
            print(landmarks)
    break

[[486 204]
 [469 194]
 [455 183]
 [443 177]
 [430 175]
 [466 169]
 [474 159]
 [478 161]
 [478 165]
 [474 169]
 [481 158]
 [484 161]
 [485 167]
 [481 171]
 [486 160]
 [488 163]
 [488 167]
 [487 174]
 [489 165]
 [489 165]
 [489 168]]
[[485 201]
 [468 191]
 [453 180]
 [440 174]
 [425 172]
 [464 167]
 [475 158]
 [480 159]
 [481 163]
 [472 169]
 [480 158]
 [486 161]
 [489 166]
 [479 171]
 [485 161]
 [489 162]
 [490 166]
 [486 174]
 [487 164]
 [488 164]
 [489 166]]
[[483 196]
 [465 186]
 [451 177]
 [439 171]
 [424 169]
 [462 165]
 [471 156]
 [476 155]
 [478 158]
 [471 166]
 [477 156]
 [482 157]
 [484 161]
 [478 168]
 [482 159]
 [486 159]
 [488 161]
 [485 171]
 [485 162]
 [487 161]
 [488 164]]
[[477 188]
 [460 180]
 [445 171]
 [433 167]
 [420 165]
 [458 165]
 [466 161]
 [472 159]
 [475 160]
 [468 166]
 [474 161]
 [479 160]
 [482 163]
 [475 168]
 [479 161]
 [483 159]
 [485 160]
 [481 170]
 [483 163]
 [484 161]
 [485 162]]
4


In [13]:
cv2.destroyAllWindows()